### ISSUE TITLE
List Connections database in Request doesn't equal with role access

### ISSUE THREAD

**Issue by sapisuper** [kviklet/kviklet#139]
Hi, 

I tried limit access to database from specified role but not reflacted in List Connection. There still showing all connection. 

Lets say I have Connection A, B , C and Role DEV C only have access to Connection C. 

Expected result : Role DEV C only have 1 connection database which is Connection C 

Current result : Role DEV C have all Connection A, B, C 

Additional information, Role Dev C is created by my self. I just remove Developer Role and Admin Role from user that only access Connection C

**Comment by sapisuper** [comment]
@Askir can you try without default role ? I mean create new role and sign to user

**Comment by sapisuper** [comment]
@Askir I can confirm with default role it's work. but the issue when you create new role

**Comment by Askir** [comment]
It also works with a custom role for me:
This is what the user sees.
<img width="400" alt="Screenshot 2024-06-18 at 15 59 03" src="https://github.com/kviklet/kviklet/assets/10251955/03048ca7-82a4-4c4e-9088-02db7532e8b7">


This is the permissions of the custom role
<img width="802" alt="Screenshot 2024-06-18 at 15 59 24" src="https://github.com/kviklet/kviklet/assets/10251955/e87226aa-60dd-4320-89de-9f936448bc83">

These are the permissions of the default role:
<img width="802" alt="Screenshot 2024-06-18 at 15 59 34" src="https://github.com/kviklet/kviklet/assets/10251955/eddb096e-f01d-454e-bd52-3cb09e03c9c3">


Can you show me your exact role setup? So that I can try to reproduce it?

**Comment by sapisuper** [comment]
@Askir Thanks for the update, I miss part in default role to remove the connection policy, currently work for me 👍 

but I found minor issue in section Connection Policy, The Selector is pointed to Connection ID but if you click it the result in Selector is Connection Name which is result will be not matches connections

**Comment by Askir** [comment]
Whoops, Should also be fixed in 0.4.2. Glad that it works now!

**Comment by sapisuper** [comment]
@Askir ok thanks will check later
