### ISSUE TITLE
Ability to abort queries

### ISSUE THREAD

**Issue by DerkSchooltink** [kviklet/kviklet#164]
When your query has been approved, and you execute it, you might come to the conclusion that there's too much impact. For that reason, a running query should be able to be aborted via the interface.

**Comment by Askir** [comment]
Good one 👍 thanks for the suggestion.
A typical issue that you don't really run into if your tables are not very large.

Will look into this.

**Comment by Askir** [comment]
@DerkSchooltink just merged.

Note: I think this is the first feature I built (other than the postgres proxy) that relies on a single container being spun up, since i now track the executing statements in Memory to allow cancellation from another thread.

So if you have a multi-instance deployment you'd need some way of routing the requests to the same instance (e.g. use the session cookie for that).

It could also be changed to track executing statements in the kviklet postgres database if this becomes a real concern though.

**Comment by DerkSchooltink** [comment]
Awesome, this is a great feature to be added. Good addition though that this not usable in HA setups. I don't run such a setup, but good to know regardless. Massive thanks for all the hard work so far!

**Comment by Askir** [comment]
Thank you for the kind words.
I think most teams are too small to really care about a HA setup right now, and I mean worst case you just have to click the cancel button a few more times until it ends up at the correct instance.

But I'll change that once someone complains. I just rather spend more time right now on additional features, rather than worrying about scaling before I even hit that problem.
