### ISSUE TITLE
Cors error when deploy on kubernetes

### ISSUE THREAD

**Issue by adhithia-irvan** [kviklet/kviklet#186]
I have error when login to kviklet. can config cors? if i use safari not have error, running normally. but im use chrome and firefox error.

```
Failed to login
Unexpected token 'I', "Invalid CORS request" is not valid JSON
```

<img width="964" alt="Screenshot 2024-08-14 at 13 06 23" src="https://github.com/user-attachments/assets/59c5e75b-9c55-43bd-a2c1-b0a20c1ce0a2">

**Comment by Askir** [comment]
Huh, that's a new one. 
Kviklets CORS policy is configured quite strictly as the frontend and backend are both running under the same domain name. So far this has worked well though.
Do you have any redirects in place before requests hit the pod?

**Comment by adhithia-irvan** [comment]
yes, but redirect ingress from http to https. does it matter?

**Comment by Askir** [comment]
No it shouldn't, hmm. I merged a PR that will allow you to configure the allowed origins yourself via an env variable, so you can maybe update your image and try setting it to your domain name and see if that helps:
```
CORS_ALLOWEDORIGINS=https://your.domain (you can add multiple separated by comma)
```
My suspicion is that some headers are not forwarded correctly by your ingress though.

**Comment by landbaychrisburrell** [comment]
Hi

I'm having a similar issue locally, when simply using a different port (because other ports are in use) - and also wondering about when we move to production. I have pulled the latest docker image but I don't think the above has made a difference:

### Locally
```
 docker run -e POSTGRES_PASSWORD=secrect -e POSTGRES_USER=postgres -p 5432:5432 postgres:16.4

 docker run -d -e SPRING_DATASOURCE_PASSWORD=secrect -e SPRING_DATASOURCE_USERNAME=postgres -e SPRING_DATASOURCE_URL=jdbc:postgresql://host.docker.internal:5432/kviklet -e INITIAL_USER_EMAIL=admin@example.com -e INITIAL_USER_PASSWORD=someverysecurepassword  -p 8080:80 ghcr.io/kviklet/kviklet:main -e CORS_ALLOWEDORIGINS=http://localhost:8080
```

Then in the browser, I go to http://localhost:8080 but two things look wrong:
* the browser itself prevents the CORS request as it omits the port

![image](https://github.com/user-attachments/assets/99362141-cccc-43b5-a165-9a2592a8be9d)

![image](https://github.com/user-attachments/assets/b5cf5e46-d84e-4ce4-9a1f-42a7d7d1ae12)

## On UAT/production
I'm concerned that as above, I may have issues around CORS/port switch. My (simplified) set-up will be as follows:
* Request from browser to https://kviklet.public
* Forward to Load balancer
* Forwards to proxying web servers as http://kviklet.internal (not TLS termination here/port change)
* Web server forwards to pod on EKS (non priveleged port so not going to be port 80)

Perhaps you can confirm what's going on with the local scenario and let me know if i might have errors on the cloud deployment scenario?

In particular, the ```ServerUrlInterceptor``` doesn't seem to cater for port changes between the 'browser' and the proxied request?

Cheers
Chris

**Comment by Askir** [comment]
Hey @landbaychrisburrell, Thank you for the additional details.

The container is indeed designed to work on the standard ports, it assumes that you run on 80 or 443 right now. The reason this shows up as a CORS error is because if you host the app on e.g. 8080 but the frontend tries to request on port 80/443 (which it always will), the browser doesn't like that and flags it as cross origin. But the request wouldn't reach the correct server anyways, since the port has been mapped.


I will look into allowing other ports, at least for experimentation this seems like a common setup (I also have things running on 80).
____
**On your specific concerns regarding proxies:**

Since CORS is mostly a browser concept sending requests through different load balancing proxies should not cause any issues. Once the browser allows sending the request, you should be allowed to do anything you want with it routing wise.
So unless you plan to run Kviklet on a nonstandard port in your environment, I wouldn't expect any issues.

**Comment by Askir** [comment]
@adhithia-irvan are you also running on a different port than 80/443? Or is your problem a different one?

**Comment by Askir** [comment]
The whole CORS check on server side that spring does seems to be a spring/enterprise special. I am considering just disabling that somehow. The important part of CORS is that the headers are set correctly so the browser can prevent CSRF attacks. Doing the backend checks is nice for really old browsers, but honestly not really necessary and will lead to a lot of issues the more reverse proxies are configured in front of the container.

By the nature of Kviklets mission, I would expect the networking setups to differ widely and even if I would manage to correctly respect and X-forwarded-xyz headers, it would be a big challenge to always configure every proxy correctly. For very questionable benefit of these server side CORS checks.

So I'll try to find a good way of disabling these. Honestly, I wasn't even aware that Spring security does this. I thought this was the usual Chrome refuses to even send the request CORS issue at first, sorry for giving somewhat misleading answers for this but it was new for me as well.

___
The more I work with Spring and Spring Security the more I come to dislike it, it's really a pain to configure correctly. I chose JVM for the JDBC connectors and to their credit, these seem to work really well. But everything around it... is a bit of a pain. At some point I might try rewrite the whole thing in Go or Rust 😂 although no idea if there exist more sensible security libraries for those.

**Comment by Askir** [comment]
Alright I just merged this change now, there is no longer any CORS restrictions on the backend site. Everything is browser enforced now. Hope that fixes the reported issues here!
