### ISSUE TITLE
Questions on Access Control and Functionality

### ISSUE THREAD

**Issue by marridecano** [kviklet/kviklet#202]
Hi team,

While using the tool, we found the following:

- User A(dev role) raises an Access request, User B(admin role) then approves request. User B is able to access this session and run queries. Is this expected behaviour? Shouldn't only user A be able to access the session and run queries?

- Additionally, any user is able to access an approved session ie User C(dev role) will be able to access the session that was raised above. Can we only allow the user that has raised the session to have access to the session? Currently, we have 2 set of users who have admin access(write access) and others with read only access. The current behaviour of Kviklet, it means we could only give access to those who already have write access. We would like users with read only access to raise queries and have this approved, instead of all users being able to access approved sessions. 

- We can only run one query at a time - is running multiple queries in the roadmap?

Kind regards,
Marri

**Comment by Askir** [comment]
This is a good question.
I went back and forth between having explicit execute permissions and having only users be able to execute their own requests.
The idea of an execute permission, would allow a user to raise a request but only someone with the correct permission e.g. admins would be able to execute it.

I thought I decided against this and instead have users be able to only execute their own requests but I checked the code and it was in a messy in between state which allowed this behaviour that you described, so thank you very much for raising it.

I fixed this now in #204, users can now only execute their own requests (again?). And this also means during an existing session only the user requesting access can execute queries.
____

Regarding:
> We can only run one query at a time - is running multiple queries in the roadmap?

Could you elaborate a bit on this? A running session can only run one query at a time right now, because I use the requests id to allow cancellation of the query. What exactly would be the use case for running multiple statements at the same time from one session? Why not run them one after another?

**Comment by marridecano** [comment]
Hi Askir,

Thank you for your prompt response. 

In regards to running multiple queries in one go, we want to run multiple sql queries separated with ; ie.
```
select * from people;
select 1
```

Being able to run the query this way guarantees atomicity, reduces the number of connections established with db and makes it easier to keep track of queries that are dependent on each other.

Kind regards,
Marri

**Comment by Askir** [comment]
Okay I tried this, and it works fine on postgresql but it doesn't work on mysql unless you se the jdbc property: `allowMultiQueries=true`. 


<img width="1060" alt="Screenshot 2024-08-22 at 18 08 46" src="https://github.com/user-attachments/assets/bfc6d08d-0cde-474f-8c67-818386a8e51b">

Then it works and you can scroll through the results, sorry I usually just test things manually with postgres and assume that the other jdbc drivers work the same, sometimes that's not the case 😅 
I'll make this a default config for future connections.

<img width="748" alt="Screenshot 2024-08-22 at 18 09 18" src="https://github.com/user-attachments/assets/72ae1742-b5c7-4f89-ab50-9fcad62a4bfb">

**Comment by Askir** [comment]
Made it the default now, thanks for raising the problem!
