### ISSUE TITLE
Add health check endpoint

### ISSUE THREAD

**Issue by DerkSchooltink** [kviklet/kviklet#232]
### Issue: Request for Health Check Endpoint

**Description:**
I need an endpoint on your service to add a health check to determine if I need to kill/restart the application.

**Requirements:**
- The endpoint should return the health status of the application.
- The endpoint should be lightweight and not impact the application's performance.

**Use Case:**
This endpoint will be used to monitor the application's health and make decisions on whether to kill or restart the application based on the health status.

**Example:**
I think most suitable would be an endpoint in the root called `/healthy` that just returns a 2xx response code when the app is up and running. 

**Additional Information:**
Please provide any necessary documentation or examples on how to integrate this endpoint into our monitoring system. 

Thank you!

**Comment by Askir** [comment]
Hi there,
Thanks for the detailed feature request 😄

There is already a `/config` endpoint which the frontend uses to determine the configured SSO method. This would not be reachable if the application is misconfigured and otherwise returns a 200. So if you need something quickly, this is probably a good solution.

But I do see the point of a separate `/healthy` endpoint with a few more details. I'm just wondering in what case the endpoint would be reachable but doesn't return a 200. Currently Kviklet doesn't even start if the DB connection fails (as it runs migrations on startup), so that's not a typical case.

It could of course test all configured DB connections, but i think this is quite expensive of an operation for a health endpoint and has little to do with how Kviklet itself is doing.

Happy about any ideas here, otherwise I'll just add a `/healthy` endpoint without any detailed response and expand on it when required.

**Comment by DerkSchooltink** [comment]
I think a simple endpoint is sufficient 👍

**Comment by Askir** [comment]
Added in #233

**Comment by Askir** [comment]
@santy1402 you can use the `:main` image or a specific commit sha as the docker tag for now. I am a bit slower on this since I started working full-time again and have still a few things that I want to finish before I release 0.6. Sorry for the trouble.
