### ISSUE TITLE
LDAP authentication

### ISSUE THREAD

**Issue by eduardo-mbochip** [kviklet/kviklet#235]
Hello,

I'm having problems logging into Kviklet using LDAP. I added all my LDAP information to the Docker-compose-yml file, but it still gives an error.

Checking the logs generated by Docker shows this error below:

_2024-09-12T18:33:42.741Z DEBUG 8 --- [nio-8081-exec-4] o.s.s.l.a.BindAuthenticator : Failed to bind with any user DNs [ ]_

Can you help me with what might be causing this error?

Thank you!

**Comment by Askir** [comment]
Hey Eduardo,
I am not an LDAP expert either sadly (heavily prefer OIDC based SSO) but I just checked and my setup it still works.
My config is the one from the readme:
```
LDAP_ENABLED=true
LDAP_URL=ldap://localhost:389
LDAP_BASE=dc=kviklet,dc=dev
LDAP_PRINCIPAL=cn=admin,dc=kviklet,dc=dev
LDAP_PASSWORD=admin
LDAP_UNIQUE_IDENTIFIER_ATTRIBUTE=uid
LDAP_EMAIL_ATTRIBUTE=mail
LDAP_FULL_NAME_ATTRIBUTE=cn
LDAP_USER_OU=people
```

And my LDIF export looks like this:
```
# Entry 1: cn=Jascha Beste,ou=people,dc=kviklet,dc=dev
dn: cn=Jascha Beste,ou=people,dc=kviklet,dc=dev
cn: Jascha Beste
gidnumber: 500
givenname: Jascha
homedirectory: /home/users/jbeste
mail: jascha@kviklet.dev
objectclass: inetOrgPerson
objectclass: posixAccount
objectclass: top
sn: Beste
uid: jbeste
uidnumber: 1000
userpassword: {MD5}somehash
```

Could you give me this info so I can try to help you?

**Comment by Askir** [comment]
Just as additional info, the error message basically means that the LDAP connection couldn't find any entry for your userid. Which probably means you've either configured the `LDAP_UNIQUE_IDENTIFIER_ATTRIBUTE` wrong or the user youre trying to login with is not part of the organizational unit that you have configured.

**Comment by brunorolim-mbochip** [comment]
Hello @Askir! Hope you are doing well. 

Just for context, we use FreeIPA over here, and it does not have directly the same concept of OUs as OpenLDAP or Active Directory. Our issue is that on the function that performs the user search, you have configured it to expect specifically the string "ou=", followed by the env variable. This code is from SecurityConfig.kt.

```fun ldapAuthenticationProvider(): LdapAuthenticationProvider {
        val userSearch = FilterBasedLdapUserSearch(
            "ou=${ldapProperties.userOu}",
            "(${ldapProperties.uniqueIdentifierAttribute}={0})",
            contextSource,
        )

        val authenticator = BindAuthenticator(contextSource).apply {
            setUserSearch(userSearch)
        }
```
        
And since our LDAP does not use it, the search was a dead end. I have built a custom docker image, only changing this first string from:

`"ou=${ldapProperties.userOu}"`

to 

`"cn=${ldapProperties.userOu}"`

With this change, applying a valid cn and keeping the other variables as we were testing, it worked as expected!

I wanted to ask you if there's a chance you could change this piece of code so there's a possibility to edit which parameter to use, other than just "OU". Or if I just continue with my custom image for now, since maybe it's an isolated case. 

In any way, we are thrilled to start using Kviklet. Let me know if you want some feedback later.

**Comment by Askir** [comment]
Hi Bruno,
Thank you very much for the detailed analysis. I wasn't aware that there are LDAP implementations out there without organizational units are a core construct.
I didn't quite go with your approach but I have added an environment variable `LDAP_SEARCH_BASE` that allows you to override the search base for all users altogether in #238. So in your case you can set this to e.g. `cn=users`, the userOu is then ignored. I hope this helps.

Again, thank you very much for raising this. Always happy about any further feedback you might have!

**Comment by niklju** [comment]
@brunorolim-mbochip @eduardo-mbochip Hi, did you ever get Kviklet working with your FreeIPA setup? Do you mind sharing your config or any advice, because I can't seem to get it working, and it's driving both me and @Askir nuts.

https://github.com/kviklet/kviklet/issues/277
