### ISSUE TITLE
Keep record of output text from UPDATE/INSERT/DELETE type queries

### ISSUE THREAD

**Issue by VIDGuide** [kviklet/kviklet#91]
I understand saving/keeping the output for a SELECT would be too difficult/large/complex, but from the audit side of things, it would be good to know the rows affected messages. 

Our current ISO compliance includes us screenshotting the output of "10 rows affected" from a query executed on production, and keeping that as our artefact, in this case, the audit trail is great that there is the query record & approval trail, but it would be ideal if it also captured the return/result text.

**Comment by Askir** [comment]
I suppose this is just the way you currently handle this and not strictly required by the auditors?
Still sounds like a reasonable request to me, I'll have a look.

Just out of curiosity are you running on one of the big 3 cloud providers? I was thinking about an option to allow saving a full audit log in text form on blob storage, this could then also include the select results.

**Comment by Askir** [comment]
One problem that I currently have with this, is that Kviklet allows you to run multiple statements in a single request.

That means that you can mix selects with updates and inserts or even DDL statements. I already added https://github.com/JSQLParser/JSqlParser to enable the explain feature, and I can probably use it again to figure out which part of a request is an insert and which is an update etc.
But it also probably means if somehow a statement is not parsable by JSQLParse (e.g. because you use something too specific to your SQL engines dialect) you wont be able to execute it at all.

That's not very pretty I think, maybe I need to make this configurable at least. Using the Parser is a bit risky anyways, if there is an error somewhere in it the "Explain" Button could already accidentally execute real SQL without the approval requirements being fulfilled.
Will think a bit more about it, maybe there is also another way without parsing the SQL.

**Comment by Askir** [comment]
Actually Kviklet already differentiates the different kind of SQL results so it should be possible to add a simple extra note for updated x rows without SQL parsing. I can probably also add it to the original execution event so that it doesn't end up as a separate event in the auditlog.

**Comment by VIDGuide** [comment]
Yeah, I think the "rows affected" is more of a "PRINT" output instead of a recordset. This should output for all operations, even SELECT. Certainly doesn't hurt to have from an audit perspective, even a select would have a record of how many rows were returned at that point in time. 

You're right, that the screenshot is "just how we handle it now", but our ISO auditor expects to have an "artefact of execution", which proves that it "did what it said it would do" when a query is manually executed against the DB. So far, he's been satisfied that a snippet of the rows effected from the query satisfies that requirement. Capturing it here would be great, and yes, attaching to the existing event record would make sense.

Re: cloud storage for the output, I think it's a separate issue/discussion, I think there is a benefit to keeping the data, if only for a period of time. Some of the queries our team would be executing may return hundreds of rows, and I'd hate for them to navigate away and then have to repeat the whole process; being able to re-retrieve the results would be a great (but separate) feature. I think the idea of wiring up cloud storage to back this makes a lot of sense! In my case, yes, we use AWS & Azure, so either would work for us. (AWS preferred) but this is more in the 'nice to have' category than need to have, where the rows affected is a bit more of a need for me.

**Comment by Askir** [comment]
I just merged #99 Which adds an expandable "Results" drawer on every execute event. This then either contains the amount of modified rows, the amount of returned rows and colums or the exact error that happened.

Looks like this:
<img width="846" alt="Screenshot 2024-04-30 at 15 14 46" src="https://github.com/kviklet/kviklet/assets/10251955/31af7752-0491-4da4-a864-f4e543c3e896">

If we end up building the "track full result on S3" feature I could simply add a link to a CSV file for Selects there as well. I'm going to focus first work on some more polishing features around the execution flow though and the permission and user settings also need an overhaul.
